# Generated by Django 4.0.4 on 2022-05-23 14:09

import account.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='about',
            field=models.TextField(blank=True, default='Write something about yourself...', max_length=255),
        ),
        migrations.AddField(
            model_name='account',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/default.jpg', max_length=255, upload_to=account.models.profile_image_path),
        ),
    ]
