# Generated by Django 4.0.4 on 2022-05-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='thread',
            name='alt',
            field=models.TextField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='thread',
            name='content',
            field=models.TextField(blank=True),
        ),
    ]
